version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      angular:
        patterns:
          - "@angular/*"
          - "@angular-devkit/*"
          - "ng-packagr"
        update-types:
          - "minor"
          - "patch"
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
