name: 📌 Bump version

on:
  workflow_dispatch:
    inputs:
      version:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Semver type of new version (major / minor / patch)'
        # Input has to be provided for the workflow to run
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "bump-version"
  bump-version:
    # The type of runner that the job will run on

    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Check out the content (source branch).  Use a deployment key so that
      # when we push changes, it will trigger the release workflow
      # run that runs on: tag. (Using the GitHub token would
      # not run the workflow to prevent infinite recursion.)
      - name: Check out source
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install npm packages
        run: npm ci

      - name: Setup Git Configuration
        run: |
          git config user.name 'Amine Matouk'
          git config user.email 'matouk.ma@gmail.com'
      - name: bump version
        run: npm version ${{ github.event.inputs.version }}

      - name: Push latest version
        run: git push origin main --follow-tags

  create-github-release:
    runs-on: ubuntu-latest
    #    needs: publish
    steps:
      - uses: actions/checkout@v2
      - name: Create Release
        uses: actions/create-release@v1

        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
