on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
#  publish:
#    name: Publish to npm
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v2
#        with:
#          node-version: '16'
#          cache: 'npm'
#      - name: Publish
#        run: |
#          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
#          npm ci
#          npm publish
#        env:
#          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
#    needs: publish
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
