name: 🚚 Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
#  publish:
#    name: Publish to npm
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v2
#        with:
#          node-version: '16'
#          cache: 'npm'
#      - name: Publish
#        run: |
#          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
#          npm ci
#          npm publish
#        env:
#          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  create-github-release:
    runs-on: ubuntu-latest
#    needs: publish
    steps:
      - uses: actions/checkout@v2
      - name: Create Release
        uses: actions/create-release@v1

        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
