name: 🚀 Publish

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm
          registry-url: https://registry.npmjs.org

      - run: npm ci
      - run: npm run build:lib
      - run: npm publish --access public
        working-directory: dist/ngx-fancier
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
