name: 🚀 Publish

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm
          registry-url: https://registry.npmjs.org

      - run: npm ci
      - run: npm run build:lib
      - run: npm publish --access public --provenance
        working-directory: dist/ngx-fancier
      - name: Upload npm debug log on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: npm-debug-log
          path: /home/runner/.npm/_logs/
